name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 准备代码
        uses: actions/checkout@v4
        
      # 安装uv环境
      - name: 安装uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.8.11"
          enable-cache: true

      - name: 准备python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: 安装依赖
        run: uv sync

      - name: 查看文件和目录结构
        run: ls -lha  

      - name: 执行代码混淆
        run: |
          . .venv/bin/activate
          # 创建输出目录
          mkdir -p dist
          # 混淆代码
          pyarmor obfuscate --output dist/main.py main.py
          # 复制必要的运行时文件
          pyarmor runtime --output dist/
          # 复制依赖
          cp -r .venv dist/

      - name: 准备打包Docker镜像的环境
        uses: docker/setup-buildx-action@v3

      - name: 打包Docker镜像
        run: |
          docker build . --file Dockerfile --tag capcut-mate:latest
